apiVersion: v1
kind: Service
metadata:
  name: titan-service
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb # High Performance Network Load Balancer
spec:
  selector:
    app: titan-inference
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000